version: 1
datastore:
  filename: app.log
scheduler:
  period_sec: 20
connection:
  retries: 5
services:
  processing: http://acit-3855.eastus.cloudapp.azure.com/processing
  reciever: http://acit-3855.eastus.cloudapp.azure.com/reciever
  storage: http://acit-3855.eastus.cloudapp.azure.com/storage
  audit: http://http://acit-3855.eastus.cloudapp.azure.com/audit_log
eventstore:
  filename: status.json
