version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181"
    hostname: zookeeper
    volumes:
      - /home/azureuser/zookeeper/data:/opt/zookeeper-3.4.13/data
    networks:
      - "api.network"
  kafka:
    image: wurstmeister/kafka
    restart: always
    command: [ start-kafka.sh ]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: acit-3855.eastus.cloudapp.azure.com # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://acit-3855.eastus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/kafka:/kafka/kafka-logs
    depends_on:
      - "zookeeper"
    networks:
      - "api.network"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - "api.network"
# Names our volume
  reciever:
    build:
      context: ../reciever/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080"
    depends_on:
      - kafka
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/reciever:/config
      - /home/azureuser/logs:/logs
    networks:
      - "api.network"
  storage:
    build:
      context: ../storage/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090"
    depends_on:
      - "kafka"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/storage:/config
      - /home/azureuser/logs:/logs
    networks:
      - "api.network"
  processing:
    build:
      context: ../processing/
      dockerfile: Dockerfile
    ports:
      - "8100"
    restart: always
    depends_on:
      - "storage"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/processing:/config
      - /home/azureuser/logs:/logs
      - processing-db:/data
    networks:
      - "api.network"
  audit_log:
    build:
      context: ../audit_log/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8110"
    depends_on:
      - "kafka"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/audit_log:/config
      - /home/azureuser/logs:/logs
    networks:
      - "api.network"
  dashboard:
    build:
      context: ../dashboard-ui/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000"
    depends_on:
      - "processing"
      - "audit_log"
    networks:
      - "api.network"
  health:
    build:
      context: ../health/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8120:8120
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/health:/config
      - /home/azureuser/logs:/logs
    networks:
      - "api.network"
  nginx:
    image: nginx:latest
    restart: always
    # Connects the conf file of the container to the conf file in our folder
    volumes:
    - /home/azureuser/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # It will start up the nginx only when all api containers have started
    depends_on:
    - "reciever"
    - "storage"
    - "processing"
    - "audit_log"
    - "dashboard"
    # Connects the port 80 of the nginx container to localhost:80 or localhost
    ports:
    - "80:80"
    networks:
    - "api.network"
volumes: 
  my-db:
  processing-db:
networks:
  api.network:
